"""HTML export for AgentDebug traces.

Generates a single self-contained HTML file with embedded CSS and JS
that displays a trace in a readable, step-by-step format.
"""

import json
from typing import Any, Dict, List, Optional

from .license import assert_export_allowed, get_watermark_html, check_trial, is_licensed


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AgentDebug Trace Report — {agent_name}</title>
<style>
  :root {{
    --bg: #0B0D1A;
    --surface: #131627;
    --surface2: #1A1D2E;
    --border: #2A2D3E;
    --text: #E2E4F0;
    --text2: #8B8FA3;
    --accent: #6366F1;
    --accent2: #22D3EE;
    --green: #34D399;
    --red: #F87171;
    --yellow: #FBBF24;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.6;
    padding: 20px;
  }}
  .container {{ max-width: 1000px; margin: 0 auto; }}
  h1 {{ color: var(--accent); font-size: 1.5em; margin-bottom: 4px; }}
  h2 {{ color: var(--accent2); font-size: 1.2em; margin: 20px 0 10px; }}
  .meta {{ color: var(--text2); font-size: 0.9em; margin-bottom: 20px; }}
  .step {{
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    margin-bottom: 12px;
    overflow: hidden;
  }}
  .step-header {{
    padding: 10px 14px;
    cursor: pointer;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-weight: 600;
    background: var(--surface2);
    user-select: none;
  }}
  .step-header:hover {{ opacity: 0.9; }}
  .step-body {{ padding: 14px; display: none; }}
  .step-body.open {{ display: block; }}
  .phase-badge {{
    display: inline-block;
    padding: 2px 8px;
    border-radius: 4px;
    font-size: 0.75em;
    font-weight: 700;
    text-transform: uppercase;
  }}
  .phase-thinking {{ background: #312E81; color: #A5B4FC; }}
  .phase-tool_call {{ background: #1E3A5F; color: #7DD3FC; }}
  .phase-deciding {{ background: #5B2E1E; color: #FDBA74; }}
  .phase-output {{ background: #1E5F3A; color: #6EE7B7; }}
  .tool-call {{
    background: var(--surface2);
    border-radius: 6px;
    padding: 10px;
    margin: 8px 0;
    font-size: 0.9em;
  }}
  .tool-call-name {{ color: var(--accent2); font-weight: 600; }}
  .tool-call-duration {{ color: var(--text2); font-size: 0.85em; }}
  pre {{
    background: #0A0C18;
    border-radius: 4px;
    padding: 10px;
    overflow-x: auto;
    font-size: 0.85em;
    font-family: 'SF Mono', 'Fira Code', monospace;
    color: var(--text);
    margin-top: 6px;
  }}
  .summary-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 12px;
    margin: 16px 0;
  }}
  .summary-card {{
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 14px;
    text-align: center;
  }}
  .summary-card .value {{
    font-size: 1.6em;
    font-weight: 700;
    color: var(--accent);
  }}
  .summary-card .label {{
    font-size: 0.8em;
    color: var(--text2);
    margin-top: 4px;
  }}
  .footer {{
    margin-top: 40px;
    color: var(--text2);
    font-size: 0.85em;
    text-align: center;
    border-top: 1px solid var(--border);
    padding-top: 20px;
  }}
  .footer a {{ color: var(--accent); text-decoration: none; }}
</style>
</head>
<body>
<div class="container">
  <h1>🔍 {agent_name}</h1>
  <div class="meta">
    Trace ID: {trace_id}<br>
    {timestamp} | {total_steps} steps | {total_duration}
  </div>

  <h2>Summary</h2>
  <div class="summary-grid">
    <div class="summary-card">
      <div class="value">{total_steps}</div>
      <div class="label">Total Steps</div>
    </div>
    <div class="summary-card">
      <div class="value">{total_tool_calls}</div>
      <div class="label">Tool Calls</div>
    </div>
    <div class="summary-card">
      <div class="value">{total_duration_value}</div>
      <div class="label">Duration (ms)</div>
    </div>
    <div class="summary-card">
      <div class="value">{token_count}</div>
      <div class="label">Tokens</div>
    </div>
  </div>

  <h2>Execution Trace</h2>
  {steps_html}

  <div class="footer">
    Generated by <a href="#">AgentDebug</a> — Agent Execution Inspector &amp; Replay SDK
  </div>
</div>
<script>
  document.querySelectorAll('.step-header').forEach(header => {{
    header.addEventListener('click', () => {{
      const body = header.nextElementSibling;
      body.classList.toggle('open');
      const arrow = header.querySelector('.arrow');
      if (arrow) arrow.textContent = body.classList.contains('open') ? '▼' : '▶';
    }});
  }});
</script>
  {watermark_html}
</body>
</html>"""


def export_to_html(trace: Dict[str, Any], output_path: Optional[str] = None) -> str:
    """Export a trace to a self-contained HTML report.

    Args:
        trace: Valid trace dictionary.
        output_path: Optional path to write the HTML file. If None,
                     returns the HTML as a string.

    Returns:
        The HTML content as a string.
    """
    assert_export_allowed()

    metadata = trace.get("metadata", {})
    steps = trace.get("steps", [])
    total_duration_ms = metadata.get("total_duration_ms", 0)
    total_tool_calls = sum(
        len(step.get("tool_calls", [])) for step in steps
    )

    # Build steps HTML
    steps_html_parts = []
    for i, step in enumerate(steps):
        phase = step.get("phase", "unknown")
        phase_label = phase.replace("_", " ").title()
        phase_class = f"phase-{phase}"

        step_index = step.get("step_index", i + 1)
        thought = step.get("thought", "")
        input_data = step.get("input", {})
        tool_calls = step.get("tool_calls", [])
        subagent_state = step.get("subagent_state")

        # Build tool calls HTML
        tool_calls_html = ""
        for tc in tool_calls:
            tool_name = tc.get("tool", "unknown")
            tool_args = tc.get("arguments", {})
            tool_result = tc.get("result", {})
            tool_duration = tc.get("duration_ms", 0)
            tool_calls_html += f"""
            <div class="tool-call">
              <div class="tool-call-name">🛠 {tool_name}</div>
              <div class="tool-call-duration">{tool_duration}ms</div>
              <details>
                <summary style="cursor:pointer;font-size:0.9em;color:var(--text2);">Arguments</summary>
                <pre>{json.dumps(tool_args, indent=2, default=str)}</pre>
              </details>
              <details>
                <summary style="cursor:pointer;font-size:0.9em;color:var(--text2);">Result</summary>
                <pre>{json.dumps(tool_result, indent=2, default=str)}</pre>
              </details>
            </div>"""

        # Build input HTML
        input_html = ""
        if input_data:
            input_html = f"""
            <details>
              <summary style="cursor:pointer;font-size:0.9em;color:var(--text2);">Input</summary>
              <pre>{json.dumps(input_data, indent=2, default=str)}</pre>
            </details>"""

        # Build thought HTML
        thought_html = ""
        if thought:
            thought_html = f"<p style='margin:8px 0;'>{_escape_html(thought)}</p>"

        # Build subagent state HTML
        subagent_html = ""
        if subagent_state:
            subagent_html = f"""
            <details>
              <summary style="cursor:pointer;font-size:0.9em;color:var(--text2);">Subagent State</summary>
              <pre>{json.dumps(subagent_state, indent=2, default=str)}</pre>
            </details>"""

        arrow = "▶"
        steps_html_parts.append(f"""
    <div class="step">
      <div class="step-header">
        <span><span class="phase-badge {phase_class}">{phase_label}</span> Step {step_index}</span>
        <span class="arrow">{arrow}</span>
      </div>
      <div class="step-body">
        {thought_html}
        {input_html}
        {tool_calls_html}
        {subagent_html}
      </div>
    </div>""")

    steps_html = "\n".join(steps_html_parts)

    # Build final HTML
    html = HTML_TEMPLATE.format(
        agent_name=_escape_html(trace.get("agent_name", "Unknown Agent")),
        trace_id=_escape_html(trace.get("trace_id", "unknown")),
        timestamp=_escape_html(trace.get("timestamp", "unknown")),
        total_steps=len(steps),
        total_duration=_format_duration(total_duration_ms),
        total_duration_value=total_duration_ms,
        total_tool_calls=total_tool_calls,
        token_count=metadata.get("token_count", 0),
        steps_html=steps_html,
        watermark_html=get_watermark_html(),
    )

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

    return html


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#039;")
    )


def _format_duration(ms: int) -> str:
    """Format milliseconds into a human-readable string."""
    if ms < 1000:
        return f"{ms}ms"
    seconds = ms / 1000
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = seconds / 60
    return f"{int(minutes)}m {int(seconds % 60)}s"
